[platformio]
default_envs = rpipico

[env:rpipico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -std=gnu++17
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_BLUETOOTH=0
    -DDFDMC_MAX_AXES=16
lib_ldf_mode = deep
lib_deps =
    symlink://../DF_DMC_Common
